name: Store caches

on:
  push:
    branches:
      - main
    paths:
      - uv.lock
  workflow_dispatch:

jobs:
  store-uv-cache:
    name: Store uv cache
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      # cache miss
      - name: Install the project
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          echo "Virtual environment cache miss - installing..."
          time uv sync --locked --all-extras --dev

      # cache hit
      - name: Validate cached environment
        if: steps.cache-venv.outputs.cache-hit == 'true'
        run: |
          echo "Virtual environment cache hit!"
          echo "Packages installed: $(uv pip list | wc -l)"